{{- if .Values.git.deployKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-deploykey
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  id_rsa: {{ .Values.git.deployKey | b64enc | quote }}
{{- end }}
