# Default values for zwave2mqtt.

image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: 0.118.5

strategy:
  type: Recreate

env: {}
  # TZ:

service:
  port:
    port: 8123
  # # Boilerplate config for code-server functionality, be sure to make changes to suit your environment
  # additionalServices:
  # - enabled: true
  #   nameSuffix: vscode
  #   type: ClusterIP
  #   port:
  #     port: 12321
  #     name: vscode
  #     protocol: TCP
  #     targetPort: 12321

# # Boilerplate config for code-server functionality, be sure to make changes to suit your environment
# additionalContainers:
# - name: vscode
#   image: codercom/code-server:3.7.2
#   imagePullPolicy: IfNotPresent
#   workingDir: /www/assets
#   args:
#   - "--port"
#   - "12321"
#   - "--auth"
#   - "none"
#   ports:
#   - name: vscode
#     containerPort: 12321
#     protocol: TCP
#   volumeMounts:
#   - name: config
#     mountPath: /www/assets
#   securityContext:
#     runAsUser: 0

ingress:
  enabled: false
  # # Boilerplate config for code-server functionality, be sure to make changes to suit your environment
  # additionalIngresses:
  # - enabled: true
  #   nameSuffix: "vscode"
  #   serviceName: home-assistant-vscode
  #   servicePort: 12321
  #   annotations:
  #     kubernetes.io/ingress.class: "nginx"
  #   hosts:
  #   - host: home-assistant-editor.local
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #   tls:
  #   - hosts:
  #     - home-assistant-editor.local

# # Enable devices to be discoverable
# hostNetwork: true

# # Enable passing thru a USB device to Home Assistant
# securityContext:
#   privileged: true

# # Enable a prometheus-operator servicemonitor
# prometheus:
#   serviceMonitor:
#     enabled: false
#     interval: 1m
#     additionalLabels: {}

persistence:
  config:
    enabled: false
    emptyDir: false
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""

# # Path to your zwave and/or zigbee device in the container
# additionalVolumeMounts:
#   - name: zwave-usb
#     mountPath: /dev/serial/by-id/usb-0658_0200-if00

# # Path to your zwave and/or zigbee device on the host
# additionalVolumes:
#   - name: zwave-usb
#     hostPath:
#       path: /dev/serial/by-id/usb-0658_0200-if00
